CREATE TABLE class_routines (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  semester VARCHAR(20) NOT NULL,
  day_of_week VARCHAR(15) NOT NULL CHECK (day_of_week IN ('Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday')),
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  room_no VARCHAR(20) NOT NULL,
  CHECK (end_time > start_time),
  UNIQUE (course_id, semester, day_of_week, start_time, end_time, room_no)
);
