CREATE TABLE "class_routines" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_id" integer REFERENCES "courses" ("id") ON DELETE CASCADE,
  "day_of_week" varchar(15),
  "start_time" time,
  "end_time" time,
  "room_no" varchar(20)
);
ALTER TABLE "class_routines" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id") ON DELETE CASCADE;
