CREATE TABLE exam_marks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE, 
  semester VARCHAR(20) NOT NULL,
  exam_type VARCHAR(30) NOT NULL CHECK (exam_type IN ('Midterm', 'Final', 'Quiz', 'Assignment', 'Presentation')),
  obtained_marks DECIMAL(5,2) DEFAULT 0.00 CHECK (obtained_marks >= 0),
  total_marks DECIMAL(5,2) NOT NULL CHECK (total_marks > 0),
  CHECK (obtained_marks <= total_marks),
  UNIQUE (student_id, course_id, semester, exam_type)
);
