CREATE TABLE "admins" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "email" varchar(100) UNIQUE NOT NULL,
  "password" varchar(255) NOT NULL,
  "role" varchar(20) DEFAULT 'admin', -- e.g., 'super_admin', 'staff'
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);
