CREATE TABLE enrollments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  semester VARCHAR(20) NOT NULL, 
  enrollment_date DATE DEFAULT CURRENT_DATE,
  status VARCHAR(20) DEFAULT 'enrolled' CHECK (status IN ('enrolled', 'completed', 'dropped', 'failed')),
  grade VARCHAR(5),
  UNIQUE (student_id, course_id, semester)
);
