CREATE TABLE "course_assignments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "teacher_id" integer REFERENCES "teachers" ("id") ON DELETE CASCADE,
  "course_id" integer REFERENCES "courses" ("id") ON DELETE CASCADE,
  "semester" varchar(20)
);
