CREATE TABLE "attendance" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" integer REFERENCES "students" ("id") ON DELETE CASCADE,
  "course_id" integer REFERENCES "courses" ("id") ON DELETE CASCADE,
  "date" date DEFAULT CURRENT_DATE,
  "status" varchar(15) -- e.g., 'Present', 'Absent'
);
ALTER TABLE "attendance" ADD FOREIGN KEY ("student_id") REFERENCES "students" ("id") ON DELETE CASCADE;
ALTER TABLE "attendance" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id") ON DELETE CASCADE;
