CREATE TABLE "courses" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(150) NOT NULL,
  "course_code" varchar(20) UNIQUE NOT NULL,
  "credits" integer NOT NULL,
  "department_id" integer REFERENCES "departments" ("id") ON DELETE CASCADE
);
