CREATE TABLE "students" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "email" varchar(100) UNIQUE NOT NULL,
  "password" varchar(255) NOT NULL,
  "department_id" integer REFERENCES "departments" ("id") ON DELETE SET NULL,
  "session" varchar(20),
  "cgpa" decimal(3,2) DEFAULT 0.0
);
