CREATE TABLE "teachers" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "email" varchar(100) UNIQUE NOT NULL,
  "password" varchar(255) NOT NULL,
  "designation" varchar(100),
  "department_id" integer REFERENCES "departments" ("id") ON DELETE SET NULL
);
