CREATE TABLE "exam_marks" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" integer REFERENCES "students" ("id") ON DELETE CASCADE,
  "course_id" integer REFERENCES "courses" ("id") ON DELETE CASCADE,
  "exam_type" varchar(30),
  "obtained_marks" decimal(5,2),
  "total_marks" decimal(5,2)
);
ALTER TABLE "exam_marks" ADD FOREIGN KEY ("student_id") REFERENCES "students" ("id") ON DELETE CASCADE;
ALTER TABLE "exam_marks" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id") ON DELETE CASCADE;
