CREATE TABLE "enrollments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" integer REFERENCES "students" ("id") ON DELETE CASCADE,
  "course_id" integer REFERENCES "courses" ("id") ON DELETE CASCADE,
  "enrollment_date" date DEFAULT CURRENT_DATE
);
