CREATE TABLE "course_assignments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "teacher_id" integer REFERENCES "teachers" ("id") ON DELETE CASCADE,
  "course_id" integer REFERENCES "courses" ("id") ON DELETE CASCADE,
  "semester" varchar(20)
);
ALTER TABLE "course_assignments" ADD FOREIGN KEY ("teacher_id") REFERENCES "teachers" ("id") ON DELETE CASCADE;
ALTER TABLE "course_assignments" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id") ON DELETE CASCADE;
