CREATE TABLE attendance (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  date DATE DEFAULT CURRENT_DATE,
  status VARCHAR(15) NOT NULL CHECK (status IN ('Present', 'Absent', 'Late', 'Excused')),
  UNIQUE (student_id, course_id, date)
);
