CREATE TABLE "departments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar,
  "code" varchar,
  PRIMARY KEY ("id")
);

CREATE TABLE "students" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar,
  "email" varchar,
  "password" varchar,
  "department_id" integer,
  "session" varchar,
  "cgpa" decimal,
  PRIMARY KEY ("id")
);

CREATE TABLE "teachers" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar,
  "email" varchar,
  "password" varchar,
  "designation" varchar,
  "department_id" integer,
  PRIMARY KEY ("id")
);

CREATE TABLE "courses" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "title" varchar,
  "course_code" varchar,
  "credits" integer,
  "department_id" integer,
  PRIMARY KEY ("id")
);

CREATE TABLE "course_assignments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "teacher_id" integer,
  "course_id" integer,
  "semester" varchar,
  PRIMARY KEY ("id")
);

CREATE TABLE "enrollments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "student_id" integer,
  "course_id" integer,
  "enrollment_date" date,
  PRIMARY KEY ("id")
);

CREATE TABLE "class_routines" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "course_id" integer,
  "day_of_week" varchar,
  "start_time" time,
  "end_time" time,
  "room_no" varchar,
  PRIMARY KEY ("id")
);

CREATE TABLE "attendance" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "student_id" integer,
  "course_id" integer,
  "date" date,
  "status" varchar,
  PRIMARY KEY ("id")
);

CREATE TABLE "exam_marks" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
  "student_id" integer,
  "course_id" integer,
  "exam_type" varchar,
  "obtained_marks" decimal,
  "total_marks" decimal,
  PRIMARY KEY ("id")
);

ALTER TABLE "students" ADD FOREIGN KEY ("department_id") REFERENCES "departments" ("id");
ALTER TABLE "teachers" ADD FOREIGN KEY ("department_id") REFERENCES "departments" ("id");
ALTER TABLE "courses" ADD FOREIGN KEY ("department_id") REFERENCES "departments" ("id");
ALTER TABLE "course_assignments" ADD FOREIGN KEY ("teacher_id") REFERENCES "teachers" ("id");
ALTER TABLE "course_assignments" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");
ALTER TABLE "enrollments" ADD FOREIGN KEY ("student_id") REFERENCES "students" ("id");
ALTER TABLE "enrollments" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");
ALTER TABLE "class_routines" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");
ALTER TABLE "attendance" ADD FOREIGN KEY ("student_id") REFERENCES "students" ("id");
ALTER TABLE "attendance" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");
ALTER TABLE "exam_marks" ADD FOREIGN KEY ("student_id") REFERENCES "students" ("id");
ALTER TABLE "exam_marks" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");